In [3]:
import math
import numpy as np
import os
import pandas as pd
import matplotlib.pyplot as plt
import collections as col
import re
import random
import sklearn
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB

In [2]:
df_train = pd.read_csv('dataset/train.csv', sep=',')
df_val = pd.read_csv('dataset/validation.csv', sep=',')

In [3]:
df_train_sub = df_train[:10000]
df_val_sub = df_val[:10000] # Contains y, where test doesn't

In [4]:
df_val_sub.columns

Index(['click', 'weekday', 'hour', 'bidid', 'logtype', 'userid', 'useragent',
       'IP', 'region', 'city', 'adexchange', 'domain', 'url', 'urlid',
       'slotid', 'slotwidth', 'slotheight', 'slotvisibility', 'slotformat',
       'slotprice', 'creative', 'bidprice', 'payprice', 'keypage',
       'advertiser', 'usertag'],
      dtype='object')

In [5]:
df_train_sub[['advertiser', 'weekday', 'click']][df_train_sub['click']== 1]

advertiser  weekday  click
1104        3358        6      1
2273        1458        1      1
2406        3386        0      1
2609        3358        4      1
4383        1458        4      1
5227        3386        5      1
6149        1458        6      1
8467        1458        6      1
8485        3386        1      1
8940        1458        5      1

In [6]:
# NB on adexchange only
#le = LabelEncoder()
#le.fit(df_train_sub['advertiser'].unique())
#col_adexchange = le.transform(df_train_sub['advertiser'])
df_train_sub['click']
features= np.column_stack([df_train_sub['weekday'].as_matrix(), df_train_sub['advertiser']])

In [7]:
features.shape

(10000, 2)

In [8]:
NB_model = GaussianNB()
NB_model.fit(features, df_train_sub['click'])

GaussianNB()

In [11]:
print(NB_model.predict([[6, 3358],[6, 3358]]))
print(NB_model.predict_proba([6, 3358]))
print(NB_model.predict_log_proba([6, 3358]))

[0 0]
[[ 0.99887108  0.00112892]]
[[ -1.12955744e-03  -6.78649409e+00]]


/Users/jamesshields/anaconda/lib/python3.5/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/jamesshields/anaconda/lib/python3.5/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [11]:
pred_lst = []
for i in range(len(df_val[:10000])):
    pred_lst.append(NB_model.predict_proba([df_val['weekday'][i], df_val['advertiser'][i]]))

/Users/jamesshields/anaconda/lib/python3.5/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/jamesshields/anaconda/lib/python3.5/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/jamesshields/anaconda/lib/python3.5/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it cont

In [12]:
pred_lst

[array([[  9.99141993e-01,   8.58006929e-04]]),
 array([[  9.99385489e-01,   6.14511449e-04]]),
 array([[  9.99610790e-01,   3.89209690e-04]]),
 array([[  9.99141993e-01,   8.58006929e-04]]),
 array([[  9.99136329e-01,   8.63671194e-04]]),
 array([[  9.99613386e-01,   3.86614269e-04]]),
 array([[  9.99447886e-01,   5.52113551e-04]]),
 array([[  9.99449275e-01,   5.50725496e-04]]),
 array([[  9.99661315e-01,   3.38685011e-04]]),
 array([[ 0.99871245,  0.00128755]]),
 array([[ 0.99887672,  0.00112328]]),
 array([[  9.99661315e-01,   3.38685011e-04]]),
 array([[ 0.99676458,  0.00323542]]),
 array([[  9.99608220e-01,   3.91780331e-04]]),
 array([[  9.99655065e-01,   3.44935176e-04]]),
 array([[  9.99608220e-01,   3.91780331e-04]]),
 array([[  9.99447886e-01,   5.52113551e-04]]),
 array([[ 0.99792994,  0.00207006]]),
 array([[ 0.99792994,  0.00207006]]),
 array([[ 0.99744539,  0.00255461]]),
 array([[ 0.99853228,  0.00146772]]),
 array([[  9.99447886e-01,   5.52113551e-04]]),
 array([[  9.9

In [13]:
pred_array= np.asarray(pred_lst).reshape(-1, 2)
pred_av = np.average(pred_array[:,1])
pred_array_norm = []
for i in range(len(pred_array[:,1])):
    pred_array_norm.append(pred_array[i,1]/ pred_av)
               

In [51]:
pred_array_norm_r = np.asarray(pred_array_norm)
pred_array_norm_r.shape

(10000,)

In [48]:
pred_array_norm_r
counter = 0
for i in range(10):
    print(pred_array_norm_r[counter])
    counter += 1
    print('-', pred_array_norm_r[i])

0.822913559408
- 0.822913559408
0.589377295991
- 0.589377295991
0.373290611615
- 0.373290611615
0.822913559408
- 0.822913559408
0.828346150217
- 0.828346150217
0.370801345904
- 0.370801345904
0.529531536264
- 0.529531536264
0.528200254675
- 0.528200254675
0.324832444354
- 0.324832444354
1.2348895316
- 1.2348895316


In [91]:
# Baseline model

def static_bid_val(df_data, bid, random_bid= False, print_YN= False):
    """
    """
    total_cost = 0
    budget = 250000
    imp_w = 0
    imp_l = 0
    clicks = 0
    lst_win = {}
    
    if random_bid== False:
        our_bid= bid
    else:
        max_bid= bid
        
    df_data_sub = df_data[['bidid', 'click', 'payprice']]

    for bidid, click, payprice in  df_data_sub.values:
        if random_bid== True:
            our_bid= random.randint(0, max_bid)
            
        if (total_cost + payprice) > budget:
            break
            
        if payprice < our_bid: #and click > 0
            imp_w += 1
            clicks += click
            total_cost += payprice
            lst_win[bidid]= [payprice, click]
            
        if payprice >= our_bid:
            imp_l += 1
            
    imp_total = len(df_data)
    try:
        imp_comp = round((imp_w+ imp_l)/ imp_total, 3)
    except: 
        imp_comp = 0
    try:
        bud_spent = total_cost/ budget
    except: 
        bud_spent = 0        
    try:
        CTR = round((clicks/ imp_w), 5)
    except:
        CTR = 0
    
    if print_YN== True:
        print('Bids won:', imp_w)
        print('Bids lost:', imp_l)
        print('% bids comp', imp_comp)
        print('Clicks:', clicks)
        print('CTR:', CTR)
        print('Total cost:', total_cost)
    
    return clicks, CTR, imp_w, imp_comp, bud_spent

clicks, CTR, imp_w, imp_comp, bud_spent= static_bid_val(df_val[:10000], 300, False, True)

Bids won: 3175
Bids lost: 1
% bids comp 0.318
Clicks: 4
CTR: 0.00126
Total cost: 249932


In [88]:
# Improved model with pCTR

def dynamic_model_val(df_data, baseline_bid, pCTR_data, print_YN='Yes'):
    total_cost = 0
    budget = 250000
    imp_w = 0
    imp_l = 0
    clicks = 0
    lst_win= []
    
    df_data_sub = df_data[['bidid', 'click', 'payprice']]
    
    counter = 0 
    for bidid, click, payprice in df_data_sub.values:
        if (total_cost + payprice) > budget:
            break
        
        our_bid = baseline_bid* pCTR_data[counter]
        counter += 1
        
        if payprice < our_bid: 
            imp_w += 1
            clicks += click
            total_cost += payprice
            
        if payprice >= our_bid:
            imp_l += 1
    
    imp_total = len(df_data)
    try:
        imp_comp = round((imp_w+ imp_l)/ imp_total, 3)
    except: 
        imp_comp = 0
    try:
        bud_spent = total_cost/ budget
    except: 
        bud_spent = 0        
    try:
        CTR = round((clicks/ imp_w), 5)
    except:
        CTR = 0
    
    if print_YN== 'Yes':
        print('Bids won:', imp_w)
        print('Bids lost:', imp_l)
        print('% bids comp', imp_comp)
        print('Clicks:', clicks)
        print('CTR:', CTR)
        print('Total cost:', total_cost)
    
    return clicks, CTR, imp_w, imp_comp, bud_spent

In [100]:
dynamic_model_val(df_val_sub, 300, pred_array_norm_r)
print('---')
static_bid_val(df_val[:10000], 300, False, True)

Bids won: 3743
Bids lost: 417
% bids comp 0.416
Clicks: 5
CTR: 0.00134
Total cost: 249984
---
Bids won: 3175
Bids lost: 1
% bids comp 0.318
Clicks: 4
CTR: 0.00126
Total cost: 249932


(4, 0.00126, 3175, 0.318, 0.999728)

In [1]:
dir(NB_model)

NameError: name 'NB_model' is not defined

In [4]:
pCTR_val = np.load('pCTR/val_lst_predict_proba.npy')

In [5]:
df_val = pd.read_csv('dataset/validation.csv', sep=',')

In [14]:
col_stack = np.column_stack((df_val, pCTR_val))

In [15]:
col_stack[0]

array([0, 5, 14, '91c6a6b9e90c0f54d3230815a5a3e22e', 1,
       'u_Vhk7C5STO8TZ3s8', 'windows_ie', '14.122.240.*', 216, 232, '1',
       'trqRTJ27Pea7gspy', 'b3f4c620ae8d3df230fca2fbed50d247', 'null',
       'mm_34061467_3440569_11228047', 300, 250, '0', '1', 0,
       '449a22cd91d9042eda3d3a1b89a22ea8', 227, 102,
       '0f951a030abdaedd733ee8d114ce2944', 3427, '10006,10063,10059,10111',
       '91c6a6b9e90c0f54d3230815a5a3e22e', 0.9992607812676795,
       0.0007392187323195925], dtype=object)

In [18]:
df_data_sub = np.column_stack((df_val[['bidid']].values, pCTR_val[:,2]))

In [20]:
for i in df_data_sub:
    print(i)
    break

['91c6a6b9e90c0f54d3230815a5a3e22e' 0.0007392187323195925]
